#!/usr/bin/env python3
"""Generate the Aurora X Zed theme family JSON (schema v0.2.0), pure-AMOLED dark."""
import json, os

# Shared aurora palette
AURORA = {
    "ice":   "#86A5FF",
    "nebula": "#C792EA",
    "cyan":   "#89DDFF",
    "green":  "#C3E88D",
    "ember":  "#F78C6C",
    "gold":   "#FFCB6B",
    "rose":   "#F07178",
    "magenta":"#DD5074",
    "text":   "#C7D5FF",
    "muted":  "#576DAF",
    "surface":"#15182B",
    "surface2":"#0C0E19",
    "line":   "#262E47",
    "black":  "#000000",
}

style = {
    # app / surfaces (pure AMOLED)
    "background": "#000000",
    "background.appearance": "opaque",
    "foreground": "#C7D5FF",
    "text": "#C7D5FF",
    "text.accent": "#86A5FF",
    "text.muted": "#576DAF",
    "text.disabled": "#3A4B6B",
    "text.placeholder": "#576DAF",
    "icon": "#86A5FF",
    "icon.accent": "#A8BEFF",
    "icon.muted": "#576DAF",
    "icon.disabled": "#3A4B6B",
    "icon.placeholder": "#576DAF",
    "accent": "#86A5FF",
    "border": "#15182B",
    "border.variant": "#262E47",
    "border.disabled": "#0C0E19",
    "border.focused": "#86A5FF",
    "border.selected": "#86A5FF",
    "border.transparent": "#00000000",

    "surface.background": "#000000",
    "elevated_surface.background": "#15182B",
    "panel.background": "#000000",
    "panel.border": "#15182B",
    "panel.focused_border": "#86A5FF",
    "panel.indent_guide": "#15182B",
    "panel.indent_guide_active": "#262E47",
    "panel.indent_guide_hover": "#3A4B6B",
    "tab_bar.background": "#000000",
    "tab.active_background": "#000000",
    "tab.inactive_background": "#000000",
    "toolbar.background": "#000000",
    "title_bar.background": "#000000",
    "title_bar.inactive_background": "#000000",

    # status / git / diagnostics
    "status_bar.background": "#000000",
    "pane.focused_border": "#86A5FF",
    "pane_group.border": "#15182B",
    "created": "#63EB90",
    "created.background": "#15331F",
    "created.border": "#63EB90",
    "modified": "#C778DB",
    "modified.background": "#2E1B33",
    "modified.border": "#C778DB",
    "deleted": "#DD5074",
    "deleted.background": "#33141C",
    "deleted.border": "#DD5074",
    "renamed": "#FFCB6B",
    "renamed.background": "#332A14",
    "renamed.border": "#FFCB6B",
    "conflict": "#FFCB6B",
    "conflict.background": "#332A14",
    "conflict.border": "#FFCB6B",
    "ignored": "#576DAF",
    "ignored.background": "#0C0E19",
    "ignored.border": "#15182B",
    "hidden": "#576DAF",
    "hidden.background": "#0C0E19",
    "hidden.border": "#15182B",
    "unreachable": "#9E3650",
    "unreachable.background": "#2A1018",
    "unreachable.border": "#9E3650",

    "info": "#82AAFF",
    "info.background": "#13233F",
    "info.border": "#82AAFF",
    "hint": "#C792EA",
    "hint.background": "#251A33",
    "hint.border": "#C792EA",
    "success": "#63EB90",
    "success.background": "#15331F",
    "success.border": "#63EB90",
    "warning": "#FFCB6B",
    "warning.background": "#332A14",
    "warning.border": "#FFCB6B",
    "error": "#DD5074",
    "error.background": "#33141C",
    "error.border": "#DD5074",
    "predictive": "#C792EA",
    "predictive.background": "#1C1430",
    "predictive.border": "#C792EA",

    "drop_target.background": "#15182B",

    # editor
    "editor.background": "#000000",
    "editor.foreground": "#C7D5FF",
    "editor.gutter.background": "#000000",
    "editor.line_number": "#3A4B6B",
    "editor.active_line_number": "#86A5FF",
    "editor.active_line.background": "#0C0E19",
    "editor.highlighted_line.background": "#0C0E19",
    "editor.invisible": "#15182B",
    "editor.wrap_guide": "#15182B",
    "editor.active_wrap_guide": "#262E47",
    "editor.indent_guide": "#15182B",
    "editor.indent_guide_active": "#3A4B6B",
    "editor.subheader.background": "#0C0E19",

    # editor document highlights
    "editor.document_highlight.read_background": "#1C2138",
    "editor.document_highlight.write_background": "#262E47",
    "editor.document_highlight.bracket_background": "#262E47",

    # scrollbars
    "scrollbar.thumb.background": "#262E47",
    "scrollbar.thumb.hover_background": "#576DAF",
    "scrollbar.thumb.border": "#00000000",
    "scrollbar.track.background": "#000000",
    "scrollbar.track.border": "#00000000",

    # search
    "search.match_background": "#576DAF",

    # terminal (full ANSI, AMOLED-tuned)
    "terminal.background": "#000000",
    "terminal.foreground": "#C7D5FF",
    "terminal.bright_foreground": "#FFFFFF",
    "terminal.dim_foreground": "#8A95B0",
    "terminal.ansi.black": "#000000",
    "terminal.ansi.red": "#DD5074",
    "terminal.ansi.green": "#63EB90",
    "terminal.ansi.yellow": "#FFCB6B",
    "terminal.ansi.blue": "#82AAFF",
    "terminal.ansi.magenta": "#C792EA",
    "terminal.ansi.cyan": "#89DDFF",
    "terminal.ansi.white": "#C7D5FF",
    "terminal.ansi.bright_black": "#576DAF",
    "terminal.ansi.bright_red": "#FF6E8A",
    "terminal.ansi.bright_green": "#8FF0B0",
    "terminal.ansi.bright_yellow": "#FFD98A",
    "terminal.ansi.bright_blue": "#A8BEFF",
    "terminal.ansi.bright_magenta": "#E0A9F5",
    "terminal.ansi.bright_cyan": "#AEF2FF",
    "terminal.ansi.bright_white": "#FFFFFF",
    "terminal.ansi.dim_black": "#0C0E19",
    "terminal.ansi.dim_red": "#9E3650",
    "terminal.ansi.dim_green": "#3F9B5C",
    "terminal.ansi.dim_yellow": "#B0893F",
    "terminal.ansi.dim_blue": "#4F69B0",
    "terminal.ansi.dim_magenta": "#8A5A94",
    "terminal.ansi.dim_cyan": "#5A97A8",
    "terminal.ansi.dim_white": "#8A95B0",

    # elements / buttons
    "element.background": "#15182B",
    "element.active": "#262E47",
    "element.hover": "#262E47",
    "element.selected": "#262E47",
    "element.disabled": "#0C0E19",
    "ghost_element.background": "#00000000",
    "ghost_element.active": "#262E47",
    "ghost_element.hover": "#15182B",
    "ghost_element.selected": "#262E47",
    "ghost_element.disabled": "#00000000",
    "link_text.hover": "#A8BEFF",
}

syntax = {
    "comment": {"color": "#546E7A", "font_style": "italic"},
    "comment.doc": {"color": "#546E7A", "font_style": "italic"},
    "text": {"color": "#C7D5FF"},
    "variable": {"color": "#EEFFFF"},
    "variable.self": {"color": "#FF5370", "font_style": "italic"},
    "variable.module": {"color": "#FF5370"},
    "constant": {"color": "#F78C6C"},
    "constant.numeric": {"color": "#F78C6C"},
    "constant.language": {"color": "#F78C6C"},
    "constant.character": {"color": "#F78C6C"},
    "constant.escape": {"color": "#89DDFF"},
    "constant.other.color": {"color": "#FFFFFF"},
    "constant.other.symbol": {"color": "#C3E88D"},
    "keyword": {"color": "#C792EA"},
    "keyword.control": {"color": "#C792EA"},
    "keyword.operator": {"color": "#89DDFF"},
    "keyword.storage": {"color": "#C792EA"},
    "keyword.modifier": {"color": "#C792EA"},
    "storage": {"color": "#C792EA"},
    "storage.type": {"color": "#C792EA"},
    "storage.modifier": {"color": "#C792EA"},
    "operator": {"color": "#89DDFF"},
    "punctuation": {"color": "#89DDFF"},
    "punctuation.definition.comment": {"color": "#546E7A", "font_style": "italic"},
    "function": {"color": "#82AAFF"},
    "function.method": {"color": "#82AAFF", "font_style": "italic"},
    "function.macro": {"color": "#C792EA"},
    "function.builtin": {"color": "#82AAFF"},
    "function.special": {"color": "#82AAFF"},
    "function.magic": {"color": "#82AAFF"},
    "function.parameter": {"color": "#EEFFFF"},
    "function.constructor": {"color": "#82AAFF"},
    "type": {"color": "#FFCB6B"},
    "type.builtin": {"color": "#FFCB6B"},
    "type.class": {"color": "#FFCB6B"},
    "type.interface": {"color": "#FFCB6B"},
    "type.enum": {"color": "#FFCB6B"},
    "type.struct": {"color": "#FFCB6B"},
    "type.trait": {"color": "#FFCB6B"},
    "type.primitive": {"color": "#FFCB6B"},
    "type.parameter": {"color": "#FFCB6B"},
    "type.alias": {"color": "#FFCB6B"},
    "type.namespace": {"color": "#FFCB6B"},
    "type.enum_member": {"color": "#FFCB6B"},
    "class": {"color": "#FFCB6B"},
    "struct": {"color": "#FFCB6B"},
    "enum": {"color": "#FFCB6B"},
    "interface": {"color": "#FFCB6B"},
    "trait": {"color": "#FFCB6B"},
    "namespace": {"color": "#FFCB6B"},
    "property": {"color": "#FFCB6B"},
    "property.object": {"color": "#EEFFFF"},
    "constructor": {"color": "#82AAFF"},
    "tag": {"color": "#F07178"},
    "tag.name": {"color": "#F07178"},
    "tag.attribute": {"color": "#C792EA"},
    "attribute": {"color": "#C792EA"},
    "attribute.builtin": {"color": "#C792EA"},
    "annotation": {"color": "#C792EA"},
    "label": {"color": "#FFCB6B"},
    "string": {"color": "#C3E88D"},
    "string.quoted": {"color": "#C3E88D"},
    "string.template": {"color": "#C3E88D"},
    "string.regexp": {"color": "#89DDFF"},
    "string.escape": {"color": "#89DDFF"},
    "string.special": {"color": "#C3E88D"},
    "string.url": {"color": "#82AAFF", "font_style": "underline"},
    "string.link": {"color": "#82AAFF", "font_style": "underline"},
    "string.doc": {"color": "#546E7A", "font_style": "italic"},
    "string.key": {"color": "#C3E88D"},
    "string.symbol": {"color": "#C3E88D"},
    "string.unquoted": {"color": "#EEFFFF"},
    "number": {"color": "#F78C6C"},
    "boolean": {"color": "#F78C6C"},
    "character": {"color": "#F78C6C"},
    "header": {"color": "#C3E88D", "font_style": "bold"},
    "heading": {"color": "#C3E88D", "font_style": "bold"},
    "heading.1": {"color": "#C3E88D", "font_style": "bold"},
    "heading.2": {"color": "#82AAFF", "font_style": "bold"},
    "heading.3": {"color": "#C792EA", "font_style": "bold"},
    "heading.4": {"color": "#C3E88D", "font_style": "bold"},
    "heading.5": {"color": "#82AAFF", "font_style": "bold"},
    "heading.6": {"color": "#C792EA", "font_style": "bold"},
    "bold": {"color": "#F07178", "font_style": "bold"},
    "italic": {"color": "#F07178", "font_style": "italic"},
    "underline": {"color": "#F78C6C", "font_style": "underline"},
    "link": {"color": "#82AAFF", "font_style": "underline"},
    "link.title": {"color": "#82AAFF"},
    "link.uri": {"color": "#82AAFF", "font_style": "underline"},
    "quote": {"color": "#65737E", "font_style": "italic"},
    "blockquote": {"color": "#65737E", "font_style": "italic"},
    "list": {"color": "#89DDFF"},
    "marker": {"color": "#89DDFF"},
    "table": {"color": "#EEFFFF"},
    "math": {"color": "#C792EA"},
    "embedded": {"color": "#C792EA"},
    "meta.diff": {"color": "#C7D5FF"},
    "meta.diff.header": {"color": "#86A5FF"},
    "diff.plus": {"color": "#C3E88D"},
    "diff.minus": {"color": "#FF5370"},
    "diff.added": {"color": "#C3E88D"},
    "diff.removed": {"color": "#FF5370"},
    "diff.modified": {"color": "#C792EA"},
    "diff.unchanged": {"color": "#576DAF"},
    "macro": {"color": "#C792EA"},
    "preprocessor": {"color": "#C792EA"},
    "module": {"color": "#FF5370"},
    "enum_member": {"color": "#FFCB6B"},
    "decorator": {"color": "#82AAFF", "font_style": "italic"},
    "escape": {"color": "#89DDFF"},
    "invalid": {"color": "#FF5370"},
    "invalid.illegal": {"color": "#FF5370"},
    "invalid.deprecated": {"color": "#FFCB6B"},
    "doc": {"color": "#546E7A", "font_style": "italic"},
    "doc.comment": {"color": "#546E7A", "font_style": "italic"},
    "punctuation.special": {"color": "#89DDFF"},
    "punctuation.bracket": {"color": "#89DDFF"},
    "punctuation.delimiter": {"color": "#89DDFF"},
    "punctuation.definition": {"color": "#89DDFF"},
    "punctuation.separator": {"color": "#89DDFF"},
    "punctuation.terminator": {"color": "#89DDFF"},
    "punctuation.section": {"color": "#89DDFF"},
}

# Multiplayer collaboration player colors (aurora ramp)
players = [
    {"background": "#0C0E19", "cursor": "#86A5FF", "selection": "#86A5FF55"},
    {"background": "#0C0E19", "cursor": "#C792EA", "selection": "#C792EA55"},
    {"background": "#0C0E19", "cursor": "#89DDFF", "selection": "#89DDFF55"},
    {"background": "#0C0E19", "cursor": "#C3E88D", "selection": "#C3E88D55"},
    {"background": "#0C0E19", "cursor": "#F78C6C", "selection": "#F78C6C55"},
    {"background": "#0C0E19", "cursor": "#FFCB6B", "selection": "#FFCB6B55"},
    {"background": "#0C0E19", "cursor": "#F07178", "selection": "#F0717855"},
    {"background": "#0C0E19", "cursor": "#DD5074", "selection": "#DD507455"},
]

accents = [
    "#86A5FF", "#C792EA", "#89DDFF", "#C3E88D", "#F78C6C", "#FFCB6B",
    "#F07178", "#DD5074", "#82AAFF", "#A8BEFF",
]

theme_family = {
    "$schema": "https://zed.dev/schema/themes/v0.2.0.json",
    "name": "Aurora X",
    "author": "Ayoub Zulfiqar (https://ayoubzulfiqar.com)",
    "themes": [
        {
            "name": "Aurora X",
            "appearance": "dark",
            "style": style,
        },
        {
            "name": "Aurora X (Pure Black)",
            "appearance": "dark",
            "style": {**style, "background": "#000000"},
        },
    ],
}

# inject syntax/players/accents into first theme (schema allows them at theme level)
# Per schema, syntax/players/accents live under each theme's object.
theme_family["themes"][0]["syntax"] = syntax
theme_family["themes"][0]["players"] = players
theme_family["themes"][0]["accents"] = accents
theme_family["themes"][1]["syntax"] = syntax
theme_family["themes"][1]["players"] = players
theme_family["themes"][1]["accents"] = accents

out = os.path.join(os.path.dirname(os.path.abspath(__file__)), "themes", "aurora-x.json")
with open(out, "w", encoding="utf-8") as f:
    json.dump(theme_family, f, indent=2, ensure_ascii=False)
    f.write("\n")
print("WROTE", out, "style keys:", len(style), "syntax keys:", len(syntax), "players:", len(players))
