#!/usr/bin/env python3
"""Generate the Aurora X Visual Studio 2026 (.vstheme) — pure-AMOLED.

Visual Studio 2026 uses Fluent semantic theme tokens:
  - <Theme Name="Aurora X" GUID="{...}" FallbackId="{Dark GUID}">
  - <Category Name="Shell" GUID="{73708ded-2d56-4aad-b8eb-73b20d3f4bff}">
  - <Category Name="ShellInternal" GUID="{5af241b7-5627-4d12-bfb1-2b67d11127d7}">
Colors are AARRGGBB (uppercase). VS2026 reads these first, then falls back to
the Dark theme (FallbackId), so we only need to supply the semantic set.
We also include a classic <Category Name="Environment"> block so the file also
works with the VS Color Theme Editor / older tooling.
"""
import os

THEME_GUID = "{a1b2c3d4-0000-40a0-9f0a-0a0a0a0a0a0a}"
DARK_FALLBACK = "{1ded0138-47ce-435e-84ef-9ec1f439b749}"
SHELL_GUID = "{73708ded-2d56-4aad-b8eb-73b20d3f4bff}"
SHELLINTERNAL_GUID = "{5af241b7-5627-4d12-bfb1-2b67d11127d7}"
ENV_GUID = "{624ed9c3-8d6b-4f3b-9c1a-8f0e1b2c3d4e}"

def a(rgb, alpha="FF"):
    """#RRGGBB -> AARRGGBB (uppercase)."""
    rgb = rgb.lstrip("#").upper()
    return (alpha + rgb).upper()

# aurora AMOLED palette
ICE = "#86A5FF"
NEBULA = "#C792EA"
CYAN = "#89DDFF"
GREEN = "#C3E88D"
EMBER = "#F78C6C"
GOLD = "#FFCB6B"
ROSE = "#F07178"
MAGENTA = "#DD5074"
TEXT = "#C7D5FF"
MUTED = "#576DAF"
BLUE = "#82AAFF"
BG = "#000000"
BG_ALT = "#0C0E19"
BG_UI = "#15182B"
LINE = "#262E47"

# ---- Shell category (Fluent semantic tokens) ----
shell = {
    # Accent ramp
    "AccentFillDefault":       a(ICE),
    "AccentFillSecondary":     a(ICE, "80"),
    "AccentFillTertiary":      a(ICE, "CC"),
    "AccentFillTransparent":   a(ICE, "33"),
    "AccentBorderDefault":     a(ICE),
    "AccentBorderSecondary":   a(ICE, "80"),
    "AccentTextDefault":       a(ICE),
    "AccentTextSecondary":     a(ICE, "CC"),
    # Background / surface fills
    "SolidBackgroundFillBase":        a(BG),
    "SolidBackgroundFillPrimary":     a(BG),
    "SolidBackgroundFillSecondary":   a(BG_ALT),
    "SolidBackgroundFillTertiary":    a(BG_UI),
    "SolidBackgroundFillQuaternary":  a(LINE),
    "SurfaceBackgroundFillDefault":   a(BG_UI),
    "SurfaceBackgroundFillSecondary": a(BG_ALT),
    "SurfaceBackgroundFillTertiary":  a(BG),
    "ControlFillDefault":       a(BG_UI),
    "ControlFillSecondary":     a(BG_ALT),
    "ControlFillTertiary":      a(LINE),
    "ControlFillTransparent":   a(BG, "00"),
    "ControlFillDisabled":      a(BG_ALT, "66"),
    "ControlFillInputActive":   a(BG_UI),
    "ControlFillBrand":         a(ICE, "33"),
    # Text fills
    "TextFillPrimary":          a(TEXT),
    "TextFillSecondary":        a(TEXT, "C8"),
    "TextFillTertiary":         a(MUTED),
    "TextFillDisabled":         a(MUTED, "80"),
    "TextFillInverse":          a(BG),
    "TextOnAccentPrimary":      a(BG),
    "TextOnAccentSecondary":    a(BG, "CC"),
    # Strokes / borders
    "StrokeDefault":            a(LINE),
    "StrokeSecondary":          a(BG_UI),
    "StrokeTertiary":           a(BG_ALT),
    "StrokeTransparent":        a(BG, "00"),
    "StrokeDisabled":           a(LINE, "66"),
    "StrokeFocus":              a(ICE),
    "StrokeAccentDefault":      a(ICE),
    "StrokeAccentSecondary":    a(ICE, "80"),
    # State fills (hover/press/selected)
    "ControlFillHover":         a(BG_UI),
    "ControlFillPressed":       a(LINE),
    "ControlFillSelected":      a(LINE),
    "ControlFillDraggedOver":   a(ICE, "33"),
    "ControlSolidFillDefault":  a(BG_UI),
    "ControlSolidFillSecondary":a(BG_ALT),
    "ControlSolidFillTertiary": a(LINE),
    "ControlSolidFillDisabled": a(BG_ALT, "66"),
    "ControlSolidFillBrand":    a(ICE),
    "ControlSolidFillError":    a(MAGENTA),
    "ControlSolidFillSuccess":  a(GREEN),
    "ControlSolidFillCaution":  a(GOLD),
    "ControlStrongFillDefault": a(BG_UI),
    "ControlStrongFillDisabled":a(BG_ALT, "66"),
    "ControlStrongFillHover":   a(LINE),
    "ControlStrongFillPressed": a(LINE),
    "ControlStrongFillSelected":a(LINE),
    "ControlStrokeDefault":     a(LINE),
    "ControlStrokeSecondary":   a(BG_UI),
    "ControlStrokeHover":       a(ICE),
    "ControlStrokePressed":     a(ICE),
    "ControlStrokeFocus":       a(ICE),
    "ControlStrokeDisabled":    a(LINE, "66"),
    # Status / communication fills
    "SuccessFillDefault":       a(GREEN, "33"),
    "SuccessFillSecondary":     a(GREEN, "1F"),
    "SuccessStrokeDefault":     a(GREEN),
    "CautionFillDefault":       a(GOLD, "33"),
    "CautionFillSecondary":     a(GOLD, "1F"),
    "CautionStrokeDefault":     a(GOLD),
    "CriticalFillDefault":      a(MAGENTA, "33"),
    "CriticalFillSecondary":    a(MAGENTA, "1F"),
    "CriticalStrokeDefault":    a(MAGENTA),
    "NeutralFillDefault":       a(MUTED, "33"),
    "NeutralFillSecondary":     a(MUTED, "1F"),
    "NeutralStrokeDefault":     a(MUTED),
    "InformationFillDefault":    a(CYAN, "33"),
    "InformationStrokeDefault": a(CYAN),
}

# ---- ShellInternal category (IDE chrome) ----
shell_internal = {
    "EnvironmentBackground":        a(BG),
    "EnvironmentBorder":            a(ICE),
    "EnvironmentIndicator":         a(MUTED, "66"),
    "EnvironmentLogo":              a(ICE),
    "EnvironmentLayeredBackground":  a(BG, "4D"),
    "EnvironmentTitleBar":         a(BG),
    "EnvironmentCommandBar":        a(BG_UI),
    "EnvironmentMenu":              a(BG_UI),
    "EnvironmentMenuItem":          a(BG_UI),
    "EnvironmentMenuItemHover":     a(LINE),
    "EnvironmentMenuItemSelected":  a(LINE),
    "EnvironmentStatus":            a(BG),
    "EnvironmentStatusBar":         a(BG),
    "EnvironmentTab":               a(BG),
    "EnvironmentTabSelected":       a(BG_ALT),
    "EnvironmentTabHover":          a(BG_UI),
    "EnvironmentScrollBar":         a(LINE),
    "EnvironmentScrollBarThumb":    a(LINE),
    "EnvironmentScrollBarThumbHover":a(MUTED),
    "EnvironmentTooltip":           a(BG_UI),
    "EnvironmentTooltipBorder":     a(LINE),
}

# ---- classic Environment category (for the VS Color Theme Editor / older tooling) ----
environment = {
    "ToolWindowBackground":     a(BG),
    "ToolWindowText":           a(TEXT),
    "ToolWindowTabSelected":    a(BG_ALT),
    "ToolWindowTabText":        a(TEXT),
    "ToolWindowTabBorder":      a(LINE),
    "EnvironmentBackground":    a(BG),
    "EnvironmentForeground":    a(TEXT),
    "TitleBarActive":           a(BG),
    "TitleBarActiveText":       a(ICE),
    "TitleBarInactive":         a(BG),
    "TitleBarInactiveText":     a(MUTED),
    "CommandBarBackground":     a(BG_UI),
    "CommandBarText":           a(TEXT),
    "CommandBarHoverOverSelectedIcon": a(ICE),
    "CommandShelfBackgroundGradientBegin": a(BG_UI),
    "CommandShelfBackgroundGradientEnd":   a(BG),
    "CommandShelfBorder":       a(LINE),
    "EnvironmentCommandBarTextActive": a(ICE),
    "EnvironmentCommandBarTextHover": a(ICE),
    "EnvironmentCommandBarTextInactive": a(MUTED),
    "EnvironmentCommandBarHoverOverSelected": a(LINE),
    "EnvironmentCommandBarSelected": a(LINE),
    "EnvironmentCommandBarIconBackground": a(BG_UI),
    "EnvironmentCommandBarGradientBegin": a(BG_UI),
    "EnvironmentCommandBarGradientEnd": a(BG),
    "EnvironmentCommandBarToolBarBorder": a(LINE),
    "EnvironmentCommandBarMenuBorder": a(LINE),
    "EnvironmentCommandBarMenuBackgroundGradientBegin": a(BG_UI),
    "EnvironmentCommandBarMenuBackgroundGradientEnd": a(BG),
    "EnvironmentCommandBarMenuText": a(TEXT),
    "EnvironmentCommandBarMenuMouseOverText": a(ICE),
    "EnvironmentCommandBarMenuMouseOverSubmenuGlyph": a(ICE),
    "EnvironmentCommandBarMenuMouseDown": a(LINE),
    "EnvironmentCommandBarMenuItemText": a(TEXT),
    "EnvironmentCommandBarMenuItemSubmenuGlyph": a(MUTED),
    "EnvironmentCommandBarOptionsText": a(MUTED),
    "EnvironmentCommandBarOverflowButtonGlyph": a(MUTED),
    "EnvironmentCommandBarDragHandle": a(LINE),
    "EnvironmentCommandBarDropDownBorder": a(LINE),
    "EnvironmentCommandBarDropDownMouseOverBackgroundBegin": a(LINE),
    "EnvironmentCommandBarDropDownMouseOverBackgroundEnd": a(LINE),
    "EnvironmentCommandBarDropDownMouseOverBorder": a(ICE),
    "EnvironmentCommandBarDropDownGlyph": a(TEXT),
    "EnvironmentCommandBarDropDownMouseOverGlyph": a(ICE),
    "EnvironmentCommandBarOptionsGlyph": a(MUTED),
    "EnvironmentCommandBarOptionsMouseOverGlyph": a(ICE),
    "EnvironmentCommandBarControlDisabled": a(MUTED, "80"),
    "EnvironmentCommandBarControlMouseOver": a(LINE),
    "EnvironmentCommandBarControlMouseDown": a(LINE),
    "EnvironmentCommandBarControlSelected": a(LINE),
    "EnvironmentCommandBarControlSelectedBorder": a(ICE),
    "EnvironmentCommandBarControlText": a(TEXT),
    "EnvironmentCommandBarControlGlyph": a(TEXT),
    "EnvironmentCommandBarControlMouseOverGlyph": a(ICE),
    "EnvironmentCommandBarControlMouseDownGlyph": a(ICE),
    "EnvironmentCommandBarControlSelectedGlyph": a(ICE),
    "EnvironmentCommandBarControlDisabledGlyph": a(MUTED, "80"),
    "EnvironmentCommandBarMenuBackground": a(BG_UI),
    "EnvironmentCommandBarMenuBorderDefault": a(LINE),
    "EnvironmentCommandBarMenuBackgroundGradient": a(BG_UI),
    "EnvironmentCommandBarMenuIconBackground": a(BG_UI),
    "EnvironmentCommandBarMenuMouseOverBackground": a(LINE),
    "EnvironmentCommandBarMenuMouseOverBorder": a(ICE),
    "EnvironmentCommandBarMenuMouseDownBackground": a(LINE),
    "EnvironmentCommandBarMenuMouseDownBorder": a(ICE),
    "EnvironmentCommandBarMenuDefault": a(TEXT),
    "EnvironmentCommandBarMenuMouseOver": a(ICE),
    "EnvironmentCommandBarMenuMouseDown": a(ICE),
    "EnvironmentCommandBarMenuSubmenuGlyph": a(MUTED),
    "EnvironmentCommandBarMenuSubmenuMouseOverGlyph": a(ICE),
    "EnvironmentCommandBarMenuTextHover": a(ICE),
    "EnvironmentCommandBarMenuTextMouseOver": a(ICE),
    "EnvironmentCommandBarMenuTextDisabled": a(MUTED, "80"),
    "EnvironmentCommandBarMenuTextSelected": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeader": a(TEXT),
    "EnvironmentCommandBarMenuTopLevelHeaderMouseOver": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeaderMouseDown": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeaderSelected": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeaderSelectedBorder": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeaderBorder": a(LINE),
    "EnvironmentCommandBarMenuTopLevelHeaderBackground": a(BG_UI),
    "EnvironmentCommandBarMenuTopLevelHeaderMouseOverBackground": a(LINE),
    "EnvironmentCommandBarMenuTopLevelHeaderMouseDownBackground": a(LINE),
    "EnvironmentCommandBarMenuTopLevelHeaderSelectedBackground": a(LINE),
    "EnvironmentCommandBarMenuTopLevelHeaderDefault": a(TEXT),
    "EnvironmentCommandBarMenuTopLevelHeaderTextHover": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeaderTextMouseOver": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeaderTextMouseDown": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeaderTextSelected": a(ICE),
    "EnvironmentCommandBarMenuTopLevelHeaderTextDisabled": a(MUTED, "80"),
    "EnvironmentCommandBarMenuBackgroundGradientMiddle": a(BG_UI),
    "EnvironmentCommandBarMenuBackgroundGradientEnd": a(BG),
    "EnvironmentCommandBarMenuBackgroundGradientBegin": a(BG_UI),
    "EnvironmentCommandBarMenuIconBackgroundGradient": a(BG_UI),
    "EnvironmentCommandBarMenuIconBackgroundMouseOver": a(LINE),
    "EnvironmentCommandBarMenuIconBackgroundMouseDown": a(LINE),
    "EnvironmentCommandBarMenuIconBackgroundSelected": a(LINE),
    "EnvironmentCommandBarMenuIconBackgroundDisabled": a(BG_ALT, "66"),
    "EnvironmentCommandBarMenuIconBorder": a(LINE),
    "EnvironmentCommandBarMenuIconBorderMouseOver": a(ICE),
    "EnvironmentCommandBarMenuIconBorderMouseDown": a(ICE),
    "EnvironmentCommandBarMenuIconBorderSelected": a(ICE),
    "EnvironmentCommandBarMenuIconBorderDisabled": a(LINE, "66"),
    "EnvironmentCommandBarMenuGlyph": a(TEXT),
    "EnvironmentCommandBarMenuGlyphMouseOver": a(ICE),
    "EnvironmentCommandBarMenuGlyphMouseDown": a(ICE),
    "EnvironmentCommandBarMenuGlyphSelected": a(ICE),
    "EnvironmentCommandBarMenuGlyphDisabled": a(MUTED, "80"),
    "EnvironmentCommandBarMenuGlyphHover": a(ICE),
    "EnvironmentCommandBarMenuGlyphPressed": a(ICE),
    "EnvironmentCommandBarMenuGlyphFocused": a(ICE),
    "EnvironmentCommandBarMenuTextFocused": a(ICE),
    "EnvironmentCommandBarMenuTextHoverFocused": a(ICE),
    "EnvironmentCommandBarMenuTextMouseDownFocused": a(ICE),
    "EnvironmentCommandBarMenuTextSelectedFocused": a(ICE),
    "EnvironmentCommandBarMenuTextDisabledFocused": a(MUTED, "80"),
    # editor surface
    "EditorBackground":         a(BG),
    "EditorForeground":         a(TEXT),
    "EditorSelectionBackground":a(LINE),
    "EditorSelectionForeground":a(ICE),
    "EditorInactiveSelectionBackground": a(BG_UI),
    "EditorInactiveSelectionForeground": a(ICE),
    "EditorLineNumber":         a("#3A4B6B"),
    "EditorLineNumberSelected": a(ICE),
    "EditorLineNumberText":     a(MUTED),
    "EditorCaret":              a(ICE),
    "EditorCaretForeground":    a(BG),
    "EditorCaretForegroundSelected": a(BG),
    "EditorIndicatorModified":  a(NEBULA),
    "EditorIndicatorAdded":     a(GREEN),
    "EditorIndicatorDeleted":   a(MAGENTA),
    "EditorGlyphMargin":        a(BG),
    "EditorGutter":             a(BG),
    "EditorRuler":              a(LINE),
    "EditorIndentGuide":        a(BG_UI),
    "EditorIndentGuideActive":  a(LINE),
    "EditorVisibleWhitespace":  a(BG_UI),
    "EditorCompletionSet":      a(BG_UI),
    "EditorCompletionSetBorder":a(LINE),
    "EditorCompletionItem":     a(TEXT),
    "EditorCompletionItemText": a(TEXT),
    "EditorCompletionItemMouseOver": a(LINE),
    "EditorCompletionItemMouseOverText": a(ICE),
    "EditorCompletionItemHighlight": a(ICE),
    "EditorCompletionItemHighlightText": a(ICE),
    "EditorCompletionItemMatch": a(ICE),
    "EditorCompletionItemMatchText": a(ICE),
    "EditorCompletionSelectedItem": a(LINE),
    "EditorCompletionSelectedItemText": a(ICE),
    "EditorCompletionSelectedItemBorder": a(ICE),
    "EditorCompletionActivePattern": a(NEBULA),
    "EditorCompletionActivePatternText": a(NEBULA),
    "EditorCompletionActivePatternBorder": a(NEBULA),
    "EditorCompletionBorder":   a(LINE),
    "EditorCompletionBox":      a(BG_UI),
    "EditorCompletionBoxBorder":a(LINE),
    "EditorTooltip":            a(BG_UI),
    "EditorTooltipBorder":      a(LINE),
    "EditorTooltipText":        a(TEXT),
    "EditorTooltipMouseOver":   a(LINE),
    "EditorTooltipMouseOverText": a(ICE),
    "EditorTooltipHeader":      a(BG_UI),
    "EditorTooltipHeaderText":  a(ICE),
    "EditorTooltipDocBackground": a(BG),
    "EditorTooltipDocText":     a(TEXT),
    "EditorTooltipDocCodeText": a(NEBULA),
    "EditorTooltipDocTextLink": a(ICE),
    "EditorTooltipDocTextBold": a(TEXT),
    "EditorTooltipDocTextItalic": a(TEXT),
    "EditorTooltipDocTextUnderline": a(TEXT),
    "EditorTooltipDocTextError": a(MAGENTA),
    "EditorTooltipDocTextWarning": a(GOLD),
    "EditorTooltipDocTextKeyword": a(NEBULA),
    "EditorTooltipDocTextComment": a(MUTED),
    "EditorTooltipDocTextString": a(GREEN),
    "EditorTooltipDocTextNumber": a(EMBER),
    "EditorTooltipDocTextPunctuation": a(CYAN),
    "EditorTooltipDocTextOperator": a(CYAN),
    "EditorTooltipDocTextType": a(GOLD),
    "EditorTooltipDocTextFunction": a(BLUE),
    "EditorTooltipDocTextVariable": a(TEXT),
    "EditorTooltipDocTextMacro": a(NEBULA),
    "EditorTooltipDocTextPreprocessor": a(NEBULA),
    "EditorTooltipDocTextLabel": a(GOLD),
    "EditorTooltipDocTextRegexp": a(CYAN),
    "EditorTooltipDocTextEscape": a(CYAN),
    "EditorTooltipDocTextTag": a(ROSE),
    "EditorTooltipDocTextAttribute": a(NEBULA),
    "EditorTooltipDocTextControlKeyword": a(NEBULA),
    "EditorTooltipDocTextOperatorKeyword": a(CYAN),
    "EditorTooltipDocTextVerbatimString": a(GREEN),
    "EditorTooltipDocTextStringLiteral": a(GREEN),
    "EditorTooltipDocTextCharacterLiteral": a(GREEN),
    "EditorTooltipDocTextNumberLiteral": a(EMBER),
    "EditorTooltipDocTextBooleanLiteral": a(EMBER),
    "EditorTooltipDocTextLineComment": a(MUTED),
    "EditorTooltipDocTextBlockComment": a(MUTED),
    "EditorTooltipDocTextXmlDocComment": a(MUTED),
    "EditorTooltipDocTextXmlDocTag": a(ROSE),
    "EditorTooltipDocTextXmlDocAttribute": a(NEBULA),
    "EditorTooltipDocTextXmlDocAttributeValue": a(GREEN),
    "EditorTooltipDocTextXmlDocCDataSection": a(GREEN),
    "EditorTooltipDocTextXmlDocComment": a(MUTED),
    "EditorTooltipDocTextXmlDocEntity": a(ROSE),
    "EditorTooltipDocTextXmlDocDelimiter": a(CYAN),
    "EditorTooltipDocTextXmlDocName": a(ROSE),
    "EditorTooltipDocTextXmlDocProcessingInstruction": a(NEBULA),
    "EditorTooltipDocTextXmlDocText": a(TEXT),
    "EditorTooltipDocTextXmlDocXmlDeclaration": a(NEBULA),
    "EditorTooltipDocTextXmlDocDocumentType": a(NEBULA),
    "EditorTooltipDocTextXmlDocEntityReference": a(ROSE),
    "EditorTooltipDocTextXmlDocCommentText": a(MUTED),
    "EditorTooltipDocTextXmlDocEntityReferenceName": a(ROSE),
    "EditorTooltipDocTextXmlDocEntityReferenceValue": a(GREEN),
    "EditorTooltipDocTextXmlDocEntityReferenceDelimiter": a(CYAN),
    "EditorTooltipDocTextXmlDocEntityReferenceNameDelimiter": a(CYAN),
    "EditorTooltipDocTextXmlDocEntityReferenceValueDelimiter": a(CYAN),
    "EditorTooltipDocTextXmlDocEntityReferenceNameText": a(ROSE),
    "EditorTooltipDocTextXmlDocEntityReferenceValueText": a(GREEN),
    "EditorErrorText":        a(MAGENTA),
    "EditorErrorBorder":      a(MAGENTA),
    "EditorWarningText":      a(GOLD),
    "EditorWarningBorder":    a(GOLD),
    "EditorInfoText":         a(CYAN),
    "EditorInfoBorder":       a(CYAN),
    "EditorHintText":         a(NEBULA),
    "EditorHintBorder":       a(NEBULA),
    "EditorSquiggleError":    a(MAGENTA),
    "EditorSquiggleWarning":  a(GOLD),
    "EditorSquiggleInfo":     a(CYAN),
    "EditorSquiggleHint":     a(NEBULA),
    "EditorDiagnosticsError": a(MAGENTA),
    "EditorDiagnosticsWarning": a(GOLD),
    "EditorDiagnosticsInfo":  a(CYAN),
    "EditorDiagnosticsHint":  a(NEBULA),
    "EditorDiagnosticsErrorText": a(MAGENTA),
    "EditorDiagnosticsWarningText": a(GOLD),
    "EditorDiagnosticsInfoText": a(CYAN),
    "EditorDiagnosticsHintText": a(NEBULA),
    "EditorDiagnosticsErrorBorder": a(MAGENTA),
    "EditorDiagnosticsWarningBorder": a(GOLD),
    "EditorDiagnosticsInfoBorder": a(CYAN),
    "EditorDiagnosticsHintBorder": a(NEBULA),
    # status bar
    "EnvironmentStatusBarText": a(ICE),
    "EnvironmentStatusBarBorder": a(LINE),
    "EnvironmentStatusBarMouseOverText": a(ICE),
    "EnvironmentStatusBarNoIdleText": a(MUTED),
    "EnvironmentStatusBarSyncSlot": a(BG),
    "EnvironmentStatusBarSyncSlotHover": a(BG_UI),
    "EnvironmentStatusBarSyncSlotPressed": a(LINE),
    "EnvironmentStatusBarSyncSlotSelected": a(LINE),
    "EnvironmentStatusBarSyncSlotText": a(ICE),
    # scrollbars (classic + modern)
    "EnvironmentScrollBarBackground": a(BG),
    "EnvironmentScrollBarThumbBackground": a(LINE),
    "EnvironmentScrollBarThumbMouseOverBackground": a(MUTED),
    "EnvironmentScrollBarArrowBackground": a(BG_UI),
    "EnvironmentScrollBarArrowGlyph": a(MUTED),
    "EnvironmentScrollBarArrowGlyphMouseOver": a(ICE),
    "EnvironmentScrollBarArrowGlyphPressed": a(ICE),
    "EnvironmentScrollBarArrowDisabledGlyph": a(MUTED, "80"),
    "EnvironmentScrollBarThumbBorder": a(BG),
    "EnvironmentScrollBarThumbMouseOverBorder": a(MUTED),
    "EnvironmentScrollBarTrackBackground": a(BG),
    "EnvironmentScrollBarTrackGlyph": a(MUTED),
    # misc chrome
    "EnvironmentToolboxBackground": a(BG_UI),
    "EnvironmentToolboxContentTabText": a(TEXT),
    "EnvironmentToolboxContentTabTextSelected": a(ICE),
    "EnvironmentToolboxContentTabTextHover": a(ICE),
    "EnvironmentToolboxContentTabBorder": a(LINE),
    "EnvironmentSideBar": a(BG),
    "EnvironmentSideBarText": a(TEXT),
    "EnvironmentSideBarItemSelected": a(LINE),
    "EnvironmentSideBarItemText": a(ICE),
    "EnvironmentSideBarItemTextHover": a(ICE),
    "EnvironmentSideBarItemBorder": a(LINE),
    "EnvironmentMainWindowBackground": a(BG),
    "EnvironmentMainWindowActiveCaption": a(BG),
    "EnvironmentMainWindowInactiveCaption": a(BG),
    "EnvironmentMainWindowText": a(ICE),
    "EnvironmentMainWindowTextInactive": a(MUTED),
    "EnvironmentMainWindowBorder": a(LINE),
    "EnvironmentMainWindowDefault": a(BG),
    "EnvironmentMainWindowDefaultText": a(TEXT),
    "EnvironmentMainWindowDefaultBorder": a(LINE),
    "EnvironmentMainWindowDefaultGlyph": a(TEXT),
    "EnvironmentMainWindowDefaultGlyphHover": a(ICE),
    "EnvironmentMainWindowDefaultGlyphPressed": a(ICE),
    "EnvironmentMainWindowDefaultGlyphDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowDefaultTextHover": a(ICE),
    "EnvironmentMainWindowDefaultTextPressed": a(ICE),
    "EnvironmentMainWindowDefaultTextDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowDefaultBorderHover": a(ICE),
    "EnvironmentMainWindowDefaultBorderPressed": a(ICE),
    "EnvironmentMainWindowDefaultBorderDisabled": a(LINE, "66"),
    "EnvironmentMainWindowDefaultBackground": a(BG),
    "EnvironmentMainWindowDefaultBackgroundHover": a(BG_UI),
    "EnvironmentMainWindowDefaultBackgroundPressed": a(LINE),
    "EnvironmentMainWindowDefaultBackgroundDisabled": a(BG_ALT, "66"),
    "EnvironmentMainWindowDefaultBackgroundSelected": a(LINE),
    "EnvironmentMainWindowDefaultBackgroundSelectedBorder": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedText": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedGlyph": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedGlyphHover": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedGlyphPressed": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedGlyphDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowDefaultBackgroundSelectedTextHover": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedTextPressed": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedTextDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowDefaultBackgroundSelectedBorderHover": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedBorderPressed": a(ICE),
    "EnvironmentMainWindowDefaultBackgroundSelectedBorderDisabled": a(LINE, "66"),
    "EnvironmentMainWindowActiveDefault": a(BG_UI),
    "EnvironmentMainWindowActiveDefaultText": a(TEXT),
    "EnvironmentMainWindowActiveDefaultBorder": a(LINE),
    "EnvironmentMainWindowActiveDefaultGlyph": a(TEXT),
    "EnvironmentMainWindowActiveDefaultGlyphHover": a(ICE),
    "EnvironmentMainWindowActiveDefaultGlyphPressed": a(ICE),
    "EnvironmentMainWindowActiveDefaultGlyphDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowActiveDefaultTextHover": a(ICE),
    "EnvironmentMainWindowActiveDefaultTextPressed": a(ICE),
    "EnvironmentMainWindowActiveDefaultTextDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowActiveDefaultBorderHover": a(ICE),
    "EnvironmentMainWindowActiveDefaultBorderPressed": a(ICE),
    "EnvironmentMainWindowActiveDefaultBorderDisabled": a(LINE, "66"),
    "EnvironmentMainWindowActiveDefaultBackground": a(BG_UI),
    "EnvironmentMainWindowActiveDefaultBackgroundHover": a(BG_UI),
    "EnvironmentMainWindowActiveDefaultBackgroundPressed": a(LINE),
    "EnvironmentMainWindowActiveDefaultBackgroundDisabled": a(BG_ALT, "66"),
    "EnvironmentMainWindowActiveDefaultBackgroundSelected": a(LINE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedBorder": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedText": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedGlyph": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedGlyphHover": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedGlyphPressed": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedGlyphDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedTextHover": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedTextPressed": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedTextDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedBorderHover": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedBorderPressed": a(ICE),
    "EnvironmentMainWindowActiveDefaultBackgroundSelectedBorderDisabled": a(LINE, "66"),
    "EnvironmentMainWindowInactiveDefault": a(BG),
    "EnvironmentMainWindowInactiveDefaultText": a(MUTED),
    "EnvironmentMainWindowInactiveDefaultBorder": a(LINE),
    "EnvironmentMainWindowInactiveDefaultGlyph": a(MUTED),
    "EnvironmentMainWindowInactiveDefaultGlyphHover": a(ICE),
    "EnvironmentMainWindowInactiveDefaultGlyphPressed": a(ICE),
    "EnvironmentMainWindowInactiveDefaultGlyphDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowInactiveDefaultTextHover": a(ICE),
    "EnvironmentMainWindowInactiveDefaultTextPressed": a(ICE),
    "EnvironmentMainWindowInactiveDefaultTextDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowInactiveDefaultBorderHover": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBorderPressed": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBorderDisabled": a(LINE, "66"),
    "EnvironmentMainWindowInactiveDefaultBackground": a(BG),
    "EnvironmentMainWindowInactiveDefaultBackgroundHover": a(BG_UI),
    "EnvironmentMainWindowInactiveDefaultBackgroundPressed": a(LINE),
    "EnvironmentMainWindowInactiveDefaultBackgroundDisabled": a(BG_ALT, "66"),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelected": a(LINE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedBorder": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedText": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedGlyph": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedGlyphHover": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedGlyphPressed": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedGlyphDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedTextHover": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedTextPressed": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedTextDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedBorderHover": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedBorderPressed": a(ICE),
    "EnvironmentMainWindowInactiveDefaultBackgroundSelectedBorderDisabled": a(LINE, "66"),
    "EnvironmentMainWindowInactiveActiveDefault": a(BG_UI),
    "EnvironmentMainWindowInactiveActiveDefaultText": a(TEXT),
    "EnvironmentMainWindowInactiveActiveDefaultBorder": a(LINE),
    "EnvironmentMainWindowInactiveActiveDefaultGlyph": a(TEXT),
    "EnvironmentMainWindowInactiveActiveDefaultGlyphHover": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultGlyphPressed": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultGlyphDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowInactiveActiveDefaultTextHover": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultTextPressed": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultTextDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowInactiveActiveDefaultBorderHover": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBorderPressed": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBorderDisabled": a(LINE, "66"),
    "EnvironmentMainWindowInactiveActiveDefaultBackground": a(BG_UI),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundHover": a(BG_UI),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundPressed": a(LINE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundDisabled": a(BG_ALT, "66"),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelected": a(LINE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedBorder": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedText": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedGlyph": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedGlyphHover": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedGlyphPressed": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedGlyphDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedTextHover": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedTextPressed": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedTextDisabled": a(MUTED, "80"),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedBorderHover": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedBorderPressed": a(ICE),
    "EnvironmentMainWindowInactiveActiveDefaultBackgroundSelectedBorderDisabled": a(LINE, "66"),
}

def color_el(name, bg, fg=None):
    parts = [f'    <Color Name="{name}">']
    if bg:
        parts.append(f'      <Background Type="CT_RAW" Source="{bg}" />')
    if fg:
        parts.append(f'      <Foreground Type="CT_RAW" Source="{fg}" />')
    parts.append('    </Color>')
    return "\n".join(parts)

def category(name, guid, colors):
    body = "\n".join(color_el(n, bg, fg) for n, (bg, fg) in colors.items())
    return f'  <Category Name="{name}" GUID="{guid}">\n{body}\n  </Category>'

# split shell dict into (bg, fg) pairs: shell has only bg
shell_pairs = {n: (v, None) for n, v in shell.items()}
shell_internal_pairs = {n: (v, None) for n, v in shell_internal.items()}
env_pairs = {n: (v, None) for n, v in environment.items()}

xml = f"""<?xml version="1.0" encoding="utf-8"?>
<Themes>
  <Theme Name="Aurora X" GUID="{THEME_GUID}" FallbackId="{DARK_FALLBACK}">
{category("Shell", SHELL_GUID, shell_pairs)}
{category("ShellInternal", SHELLINTERNAL_GUID, shell_internal_pairs)}
{category("Environment", ENV_GUID, env_pairs)}
  </Theme>
</Themes>
"""

root = os.path.dirname(os.path.abspath(__file__))
out = os.path.join(root, "Aurora X.vstheme")
with open(out, "w", encoding="utf-8") as f:
    f.write(xml)
print("WROTE", out, "shell:", len(shell), "shellInternal:", len(shell_internal), "environment:", len(environment))
