-- Aurora X — highlight groups
-- Author: Ayoub Zulfiqar (https://ayoubzulfiqar.com)
local M = {}

M.get = function()
  return {
    Normal = { fg = '#C7D5FF', bg = '#000000' },
    NormalFloat = { fg = '#C7D5FF', bg = '#15182B' },
    NormalNC = { fg = '#9AA8D6', bg = '#000000' },
    SignColumn = { fg = '#576DAF', bg = '#000000' },
    SignColumnNC = { fg = '#576DAF', bg = '#000000' },
    Cursor = { fg = '#000000', bg = '#86A5FF' },
    CursorLine = { bg = '#0C0E19' },
    CursorLineNr = { fg = '#86A5FF', bg = '#0C0E19' },
    CursorColumn = { bg = '#0C0E19' },
    ColorColumn = { bg = '#0C0E19' },
    LineNr = { fg = '#3A4B6B', bg = '#000000' },
    VertSplit = { fg = '#15182B', bg = '#000000' },
    WinSeparator = { fg = '#15182B', bg = '#000000' },
    Folded = { fg = '#576DAF', bg = '#0C0E19' },
    FoldColumn = { fg = '#576DAF', bg = '#000000' },
    IncSearch = { fg = '#000000', bg = '#86A5FF' },
    Search = { fg = '#000000', bg = '#576DAF' },
    CurSearch = { fg = '#000000', bg = '#86A5FF' },
    Visual = { bg = '#262E47' },
    VisualNOS = { bg = '#262E47' },
    VisualNC = { bg = '#262E47' },
    Substitute = { fg = '#000000', bg = '#C792EA' },
    MatchParen = { fg = '#EEFFFF', bg = '#262E47', bold = true },
    Conceal = { fg = '#576DAF', bg = '#000000' },
    Whitespace = { fg = '#15182B' },
    NonText = { fg = '#15182B' },
    SpecialKey = { fg = '#576DAF' },
    EndOfBuffer = { fg = '#000000' },
    Directory = { fg = '#82AAFF' },
    Title = { fg = '#C3E88D', bold = true },
    Question = { fg = '#C3E88D' },
    MoreMsg = { fg = '#C3E88D' },
    ModeMsg = { fg = '#86A5FF' },
    ErrorMsg = { fg = '#DD5074', bold = true },
    WarningMsg = { fg = '#FFCB6B', bold = true },
    MsgArea = { fg = '#9AA8D6' },
    MsgSeparator = { fg = '#15182B' },
    WildMenu = { fg = '#86A5FF', bg = '#15182B' },
    StatusLine = { fg = '#86A5FF', bg = '#000000', bold = true },
    StatusLineNC = { fg = '#576DAF', bg = '#000000' },
    StatusLineTerm = { fg = '#86A5FF', bg = '#000000' },
    StatusLineTermNC = { fg = '#576DAF', bg = '#000000' },
    TabLine = { fg = '#576DAF', bg = '#000000' },
    TabLineFill = { fg = '#576DAF', bg = '#000000' },
    TabLineSel = { fg = '#EEFFFF', bg = '#0C0E19', bold = true },
    Pmenu = { fg = '#C7D5FF', bg = '#15182B' },
    PmenuSel = { fg = '#86A5FF', bg = '#262E47' },
    PmenuSelBold = { bold = true },
    PmenuSbar = { bg = '#1C2138' },
    PmenuThumb = { bg = '#576DAF' },
    QuickFixLine = { fg = '#86A5FF', bg = '#262E47' },
    SpellBad = { sp = '#DD5074', undercurl = true },
    SpellCap = { sp = '#FFCB6B', undercurl = true },
    SpellRare = { sp = '#C792EA', undercurl = true },
    SpellLocal = { sp = '#89DDFF', undercurl = true },
    Terminal = { fg = '#C7D5FF', bg = '#000000' },
    TerminalCursor = { fg = '#000000', bg = '#86A5FF' },
    TermCursor = { fg = '#000000', bg = '#86A5FF' },
    TermCursorNC = { fg = '#000000', bg = '#86A5FF' },
    ToolbarLine = { fg = '#C7D5FF', bg = '#15182B' },
    ToolbarButton = { fg = '#86A5FF', bg = '#1C2138' },
    FloatBorder = { fg = '#86A5FF', bg = '#15182B' },
    FloatTitle = { fg = '#86A5FF', bg = '#15182B' },
    WinBar = { fg = '#C7D5FF', bg = '#000000' },
    WinBarNC = { fg = '#576DAF', bg = '#000000' },
    Menubar = { fg = '#C7D5FF', bg = '#15182B' },
    Scrollbar = { fg = '#576DAF', bg = '#000000' },
    Comment = { fg = '#546E7A', italic = true },
    Constant = { fg = '#F78C6C' },
    String = { fg = '#C3E88D' },
    Character = { fg = '#C3E88D' },
    Number = { fg = '#F78C6C' },
    Boolean = { fg = '#F78C6C' },
    Float = { fg = '#F78C6C' },
    Identifier = { fg = '#EEFFFF' },
    Function = { fg = '#82AAFF', bold = true },
    Statement = { fg = '#C792EA', bold = true },
    Conditional = { fg = '#C792EA' },
    Repeat = { fg = '#C792EA' },
    Label = { fg = '#FFCB6B' },
    Operator = { fg = '#89DDFF' },
    Keyword = { fg = '#C792EA', bold = true },
    Exception = { fg = '#C792EA' },
    PreProc = { fg = '#C792EA' },
    Include = { fg = '#C792EA' },
    Define = { fg = '#C792EA' },
    Macro = { fg = '#C792EA' },
    PreCondit = { fg = '#C792EA' },
    Type = { fg = '#FFCB6B' },
    StorageClass = { fg = '#C792EA' },
    Structure = { fg = '#FFCB6B' },
    Typedef = { fg = '#FFCB6B' },
    Special = { fg = '#89DDFF' },
    SpecialChar = { fg = '#89DDFF' },
    Tag = { fg = '#F07178' },
    Delimiter = { fg = '#89DDFF' },
    SpecialComment = { fg = '#546E7A', italic = true },
    Debug = { fg = '#576DAF' },
    Underlined = { fg = '#82AAFF', underline = true },
    Ignore = { fg = '#576DAF' },
    Error = { fg = '#DD5074', bold = true },
    Todo = { fg = '#FFCB6B', bold = true },
    htmlTag = { fg = '#F07178' },
    htmlEndTag = { fg = '#F07178' },
    htmlTagName = { fg = '#F07178' },
    htmlArg = { fg = '#C792EA' },
    xmlTag = { fg = '#F07178' },
    xmlEndTag = { fg = '#F07178' },
    xmlTagName = { fg = '#F07178' },
    cssPropertyName = { fg = '#82AAFF' },
    cssValueNumber = { fg = '#F78C6C' },
    @comment = { fg = '#546E7A', italic = true },
    @comment.documentation = { fg = '#546E7A', italic = true },
    @none = {  },
    @text = { fg = '#C7D5FF' },
    @text.strong = { fg = '#F07178', bold = true },
    @text.emphasis = { fg = '#F07178', italic = true },
    @text.underline = { fg = '#F78C6C', underline = true },
    @text.strike = { fg = '#576DAF', strikethrough = true },
    @text.title = { fg = '#C3E88D', bold = true },
    @text.title.1 = { fg = '#C3E88D', bold = true },
    @text.title.2 = { fg = '#82AAFF', bold = true },
    @text.title.3 = { fg = '#C792EA', bold = true },
    @text.title.4 = { fg = '#C3E88D', bold = true },
    @text.title.5 = { fg = '#82AAFF', bold = true },
    @text.title.6 = { fg = '#C792EA', bold = true },
    @text.literal = { fg = '#C792EA' },
    @text.uri = { fg = '#82AAFF', underline = true },
    @text.link = { fg = '#82AAFF', underline = true },
    @text.reference = { fg = '#82AAFF' },
    @text.note = { fg = '#89DDFF' },
    @text.warning = { fg = '#FFCB6B' },
    @text.danger = { fg = '#DD5074' },
    @text.diff.add = { fg = '#63EB90' },
    @text.diff.delete = { fg = '#DD5074' },
    @text.environment = { fg = '#C792EA' },
    @text.environment.name = { fg = '#FFCB6B' },
    @text.math = { fg = '#C792EA' },
    @text.quote = { fg = '#576DAF', italic = true },
    @text.punctuation = { fg = '#89DDFF' },
    @text.todo = { fg = '#FFCB6B', bold = true },
    @keyword = { fg = '#C792EA', bold = true },
    @keyword.coroutine = { fg = '#C792EA' },
    @keyword.function = { fg = '#C792EA', bold = true },
    @keyword.operator = { fg = '#89DDFF' },
    @keyword.import = { fg = '#C792EA' },
    @keyword.storage = { fg = '#C792EA' },
    @keyword.repeat = { fg = '#C792EA' },
    @keyword.return = { fg = '#C792EA' },
    @keyword.conditional = { fg = '#C792EA' },
    @keyword.debug = { fg = '#C792EA' },
    @keyword.exception = { fg = '#C792EA' },
    @keyword.directive = { fg = '#C792EA' },
    @keyword.directive.define = { fg = '#C792EA' },
    @constant = { fg = '#F78C6C' },
    @constant.builtin = { fg = '#F78C6C' },
    @constant.macro = { fg = '#C792EA' },
    @constant.numeric = { fg = '#F78C6C' },
    @constant.volatile = { fg = '#F78C6C' },
    @string = { fg = '#C3E88D' },
    @string.documentation = { fg = '#C3E88D' },
    @string.escape = { fg = '#89DDFF' },
    @string.special = { fg = '#89DDFF' },
    @string.regexp = { fg = '#89DDFF' },
    @character = { fg = '#C3E88D' },
    @character.special = { fg = '#89DDFF' },
    @boolean = { fg = '#F78C6C' },
    @number = { fg = '#F78C6C' },
    @number.float = { fg = '#F78C6C' },
    @type = { fg = '#FFCB6B' },
    @type.builtin = { fg = '#FFCB6B' },
    @type.definition = { fg = '#FFCB6B' },
    @type.qualifier = { fg = '#C792EA' },
    @type.annotation = { fg = '#C792EA' },
    @attribute = { fg = '#C792EA' },
    @attribute.builtin = { fg = '#C792EA' },
    @property = { fg = '#FFCB6B' },
    @field = { fg = '#EEFFFF' },
    @variable = { fg = '#EEFFFF' },
    @variable.builtin = { fg = '#82AAFF' },
    @variable.parameter = { fg = '#EEFFFF' },
    @variable.parameter.builtin = { fg = '#82AAFF' },
    @variable.member = { fg = '#EEFFFF' },
    @variable.static = { fg = '#EEFFFF' },
    @variable.global = { fg = '#EEFFFF' },
    @parameter = { fg = '#EEFFFF' },
    @namespace = { fg = '#FFCB6B' },
    @module = { fg = '#FFCB6B' },
    @label = { fg = '#FFCB6B' },
    @operator = { fg = '#89DDFF' },
    @punctuation = { fg = '#89DDFF' },
    @punctuation.delimiter = { fg = '#89DDFF' },
    @punctuation.bracket = { fg = '#89DDFF' },
    @punctuation.special = { fg = '#89DDFF' },
    @function = { fg = '#82AAFF', bold = true },
    @function.builtin = { fg = '#82AAFF', bold = true },
    @function.call = { fg = '#82AAFF' },
    @function.macro = { fg = '#C792EA' },
    @function.method = { fg = '#82AAFF', bold = true },
    @method = { fg = '#82AAFF', bold = true },
    @method.call = { fg = '#82AAFF' },
    @constructor = { fg = '#82AAFF' },
    @tag = { fg = '#F07178' },
    @tag.attribute = { fg = '#C792EA' },
    @tag.delimiter = { fg = '#89DDFF' },
    @tag.builtin = { fg = '#F07178' },
    @class = { fg = '#FFCB6B', bold = true },
    @struct = { fg = '#FFCB6B', bold = true },
    @enum = { fg = '#FFCB6B', bold = true },
    @interface = { fg = '#FFCB6B', bold = true },
    @enumMember = { fg = '#FFCB6B' },
    @event = { fg = '#C792EA' },
    @modifier = { fg = '#C792EA' },
    @storageclass = { fg = '#C792EA' },
    @structure = { fg = '#FFCB6B' },
    @include = { fg = '#C792EA' },
    @repeat = { fg = '#C792EA' },
    @conditional = { fg = '#C792EA' },
    @exception = { fg = '#C792EA' },
    @debug = { fg = '#576DAF' },
    @macro = { fg = '#C792EA' },
    @error = { fg = '#DD5074', sp = '#DD5074', undercurl = true },
    @warning = { fg = '#FFCB6B' },
    @info = { fg = '#89DDFF' },
    @hint = { fg = '#C792EA' },
    @deprecated = { fg = '#576DAF', strikethrough = true },
    @diff.plus = { fg = '#63EB90' },
    @diff.minus = { fg = '#DD5074' },
    @diff.delta = { fg = '#C792EA' },
    @lsp.type.class = { fg = '#FFCB6B', bold = true },
    @lsp.type.enum = { fg = '#FFCB6B', bold = true },
    @lsp.type.interface = { fg = '#FFCB6B', bold = true },
    @lsp.type.struct = { fg = '#FFCB6B', bold = true },
    @lsp.type.type = { fg = '#FFCB6B' },
    @lsp.type.typeParameter = { fg = '#FFCB6B' },
    @lsp.type.namespace = { fg = '#FFCB6B' },
    @lsp.type.module = { fg = '#FFCB6B' },
    @lsp.type.function = { fg = '#82AAFF', bold = true },
    @lsp.type.method = { fg = '#82AAFF', bold = true },
    @lsp.type.macro = { fg = '#C792EA' },
    @lsp.type.decorator = { fg = '#C792EA' },
    @lsp.type.enumMember = { fg = '#FFCB6B' },
    @lsp.type.property = { fg = '#FFCB6B' },
    @lsp.type.field = { fg = '#EEFFFF' },
    @lsp.type.variable = { fg = '#EEFFFF' },
    @lsp.type.parameter = { fg = '#EEFFFF' },
    @lsp.type.constant = { fg = '#F78C6C' },
    @lsp.type.number = { fg = '#F78C6C' },
    @lsp.type.string = { fg = '#C3E88D' },
    @lsp.type.boolean = { fg = '#F78C6C' },
    @lsp.type.keyword = { fg = '#C792EA', bold = true },
    @lsp.type.modifier = { fg = '#C792EA' },
    @lsp.type.operator = { fg = '#89DDFF' },
    @lsp.type.comment = { fg = '#546E7A', italic = true },
    @lsp.type.label = { fg = '#FFCB6B' },
    @lsp.type.generic = { fg = '#C7D5FF' },
    @lsp.type.builtinType = { fg = '#FFCB6B' },
    @lsp.type.selfKeyword = { fg = '#F07178', italic = true },
    @lsp.type.escapeSequence = { fg = '#89DDFF' },
    @lsp.type.formatSpecifier = { fg = '#89DDFF' },
    DiagnosticError = { fg = '#DD5074' },
    DiagnosticWarn = { fg = '#FFCB6B' },
    DiagnosticInfo = { fg = '#89DDFF' },
    DiagnosticHint = { fg = '#C792EA' },
    DiagnosticSignError = { fg = '#DD5074' },
    DiagnosticSignWarn = { fg = '#FFCB6B' },
    DiagnosticSignInfo = { fg = '#89DDFF' },
    DiagnosticSignHint = { fg = '#C792EA' },
    DiagnosticUnderlineError = { sp = '#DD5074', undercurl = true },
    DiagnosticUnderlineWarn = { sp = '#FFCB6B', undercurl = true },
    DiagnosticUnderlineInfo = { sp = '#89DDFF', undercurl = true },
    DiagnosticUnderlineHint = { sp = '#C792EA', undercurl = true },
    DiagnosticVirtualTextError = { fg = '#DD5074' },
    DiagnosticVirtualTextWarn = { fg = '#FFCB6B' },
    DiagnosticVirtualTextInfo = { fg = '#89DDFF' },
    DiagnosticVirtualTextHint = { fg = '#C792EA' },
    DiagnosticFloatingError = { fg = '#DD5074' },
    DiagnosticFloatingWarn = { fg = '#FFCB6B' },
    DiagnosticFloatingInfo = { fg = '#89DDFF' },
    DiagnosticFloatingHint = { fg = '#C792EA' },
    LspReferenceRead = { bg = '#1C2138' },
    LspReferenceText = { bg = '#1C2138' },
    LspReferenceWrite = { bg = '#262E47' },
    LspCodeLens = { fg = '#576DAF', italic = true },
    LspInlayHint = { fg = '#576DAF', bg = '#15182B' },
    LspSignatureActiveParameter = { fg = '#86A5FF', bold = true },
    TreesitterContext = { bg = '#0C0E19' },
    TreesitterContextLineNumber = { fg = '#576DAF' },
    GitSignsAdd = { fg = '#63EB90' },
    GitSignsChange = { fg = '#C792EA' },
    GitSignsDelete = { fg = '#DD5074' },
    GitSignsCurrentLineBlame = { fg = '#576DAF', italic = true },
    GitSignsAddLn = { bg = '#14331F' },
    GitSignsChangeLn = { bg = '#2E1B33' },
    GitSignsDeleteLn = { bg = '#33141C' },
    TelescopeNormal = { fg = '#C7D5FF', bg = '#000000' },
    TelescopeBorder = { fg = '#86A5FF', bg = '#000000' },
    TelescopePromptNormal = { fg = '#C7D5FF', bg = '#15182B' },
    TelescopePromptBorder = { fg = '#86A5FF', bg = '#15182B' },
    TelescopePromptTitle = { fg = '#000000', bg = '#86A5FF', bold = true },
    TelescopeResultsTitle = { fg = '#000000', bg = '#C792EA', bold = true },
    TelescopePreviewTitle = { fg = '#000000', bg = '#C3E88D', bold = true },
    TelescopeSelection = { fg = '#86A5FF', bg = '#262E47' },
    TelescopeMatching = { fg = '#86A5FF', bold = true },
    TelescopePromptPrefix = { fg = '#86A5FF' },
    NvimTreeNormal = { fg = '#C7D5FF', bg = '#000000' },
    NvimTreeFolderName = { fg = '#82AAFF' },
    NvimTreeOpenedFolderName = { fg = '#86A5FF' },
    NvimTreeRootFolder = { fg = '#86A5FF', bold = true },
    NvimTreeFileIcon = { fg = '#576DAF' },
    NvimTreeSpecialFile = { fg = '#C792EA' },
    NvimTreeGitDirty = { fg = '#C792EA' },
    NvimTreeGitNew = { fg = '#63EB90' },
    NvimTreeGitDeleted = { fg = '#DD5074' },
    NeoTreeNormal = { fg = '#C7D5FF', bg = '#000000' },
    NeoTreeDirectoryName = { fg = '#82AAFF' },
    NeoTreeGitModified = { fg = '#C792EA' },
    NeoTreeGitAdded = { fg = '#63EB90' },
    NeoTreeGitDeleted = { fg = '#DD5074' },
    WhichKey = { fg = '#86A5FF', bold = true },
    WhichKeyGroup = { fg = '#C792EA' },
    WhichKeyValue = { fg = '#C3E88D' },
    WhichKeyDesc = { fg = '#C7D5FF' },
    WhichKeySeparator = { fg = '#576DAF' },
    CmpItemAbbr = { fg = '#C7D5FF' },
    CmpItemAbbrMatch = { fg = '#86A5FF', bold = true },
    CmpItemAbbrDeprecated = { fg = '#576DAF', strikethrough = true },
    CmpItemMenu = { fg = '#576DAF' },
    CmpItemKindText = { fg = '#C7D5FF' },
    CmpItemKindMethod = { fg = '#82AAFF' },
    CmpItemKindFunction = { fg = '#82AAFF' },
    CmpItemKindConstructor = { fg = '#82AAFF' },
    CmpItemKindField = { fg = '#EEFFFF' },
    CmpItemKindVariable = { fg = '#EEFFFF' },
    CmpItemKindClass = { fg = '#FFCB6B' },
    CmpItemKindInterface = { fg = '#FFCB6B' },
    CmpItemKindModule = { fg = '#FFCB6B' },
    CmpItemKindProperty = { fg = '#FFCB6B' },
    CmpItemKindKeyword = { fg = '#C792EA' },
    CmpItemKindSnippet = { fg = '#C792EA' },
    CmpItemKindColor = { fg = '#89DDFF' },
    CmpItemKindFile = { fg = '#82AAFF' },
    CmpItemKindReference = { fg = '#89DDFF' },
    CmpItemKindFolder = { fg = '#82AAFF' },
    CmpItemKindEnum = { fg = '#FFCB6B' },
    CmpItemKindConstant = { fg = '#F78C6C' },
    CmpItemKindStruct = { fg = '#FFCB6B' },
    CmpItemKindTypeParameter = { fg = '#FFCB6B' },
    IndentBlanklineChar = { fg = '#15182B' },
    IndentBlanklineContextChar = { fg = '#262E47' },
    IndentBlanklineSpaceChar = { fg = '#15182B' },
    lualine_a_normal = { fg = '#000000', bg = '#86A5FF', bold = true },
    lualine_b_normal = { fg = '#86A5FF', bg = '#15182B' },
    lualine_c_normal = { fg = '#C7D5FF', bg = '#000000' },
    lualine_a_insert = { fg = '#000000', bg = '#C3E88D', bold = true },
    lualine_a_visual = { fg = '#000000', bg = '#C792EA', bold = true },
    lualine_a_replace = { fg = '#000000', bg = '#F78C6C', bold = true },
    lualine_a_command = { fg = '#000000', bg = '#FFCB6B', bold = true },
    lualine_a_inactive = { fg = '#576DAF', bg = '#15182B' },
    lualine_b_inactive = { fg = '#576DAF', bg = '#15182B' },
    lualine_c_inactive = { fg = '#576DAF', bg = '#000000' },
    lualine_z_normal = { fg = '#86A5FF', bg = '#15182B' },
    NotifyERRORBorder = { fg = '#DD5074' },
    NotifyWARNBorder = { fg = '#FFCB6B' },
    NotifyINFOBorder = { fg = '#89DDFF' },
    NotifyDEBUGBorder = { fg = '#576DAF' },
    NotifyTRACEBorder = { fg = '#C792EA' },
    NotifyERRORIcon = { fg = '#DD5074' },
    NotifyWARNIcon = { fg = '#FFCB6B' },
    NotifyINFOIcon = { fg = '#89DDFF' },
    NotifyDEBUGIcon = { fg = '#576DAF' },
    NotifyTRACEIcon = { fg = '#C792EA' },
    NotifyERRORTitle = { fg = '#DD5074' },
    NotifyWARNTitle = { fg = '#FFCB6B' },
    NotifyINFOTitle = { fg = '#89DDFF' },
    NotifyDEBUGTitle = { fg = '#576DAF' },
    NotifyTRACETitle = { fg = '#C792EA' },
    DiffAdd = { fg = '#63EB90', bg = '#14331F' },
    DiffChange = { fg = '#C792EA', bg = '#2E1B33' },
    DiffDelete = { fg = '#DD5074', bg = '#33141C' },
    DiffText = { fg = '#EEFFFF', bg = '#262E47' },
    diffAdded = { fg = '#63EB90' },
    diffChanged = { fg = '#C792EA' },
    diffRemoved = { fg = '#DD5074' },
    DiffviewFilePanelTitle = { fg = '#86A5FF', bold = true },
    DiffviewFilePanelCounter = { fg = '#C792EA' },
    RenderMarkdownCode = { fg = '#C792EA', bg = '#0C0E19' },
    RenderMarkdownHeading = { fg = '#C3E88D', bold = true },
    RenderMarkdownTableHead = { fg = '#86A5FF' },
    MarkdownCode = { fg = '#C792EA' },
    BufferLineFill = { bg = '#000000' },
    BufferLineBackground = { fg = '#576DAF', bg = '#000000' },
    BufferLineBufferSelected = { fg = '#86A5FF', bg = '#0C0E19', bold = true },
    BufferLineIndicatorSelected = { fg = '#86A5FF' },
    BufferLineModified = { fg = '#C792EA' },
    BufferLineSeparator = { fg = '#15182B' },
    BufferLineTabSelected = { fg = '#86A5FF', bg = '#0C0E19' },
    NoiceCmdlineIcon = { fg = '#86A5FF' },
    NoiceCmdlinePopup = { fg = '#C7D5FF', bg = '#15182B' },
    NoiceCmdlinePopupBorder = { fg = '#86A5FF', bg = '#15182B' },
    NoiceConfirmation = { fg = '#C7D5FF', bg = '#15182B' },
    MiniIndentscopeSymbol = { fg = '#262E47' },
    MiniPickNormal = { fg = '#C7D5FF', bg = '#000000' },
    MiniPickBorder = { fg = '#86A5FF' },
    MiniPickTitle = { fg = '#000000', bg = '#86A5FF', bold = true },
    MiniStatuslineDevinfo = { fg = '#C7D5FF', bg = '#15182B' },
    MiniStatuslineFilename = { fg = '#C7D5FF', bg = '#000000' },
    MiniStatuslineInactive = { fg = '#576DAF', bg = '#15182B' },
    MiniStatuslineModeNormal = { fg = '#000000', bg = '#86A5FF', bold = true },
    MiniStatuslineModeInsert = { fg = '#000000', bg = '#C3E88D', bold = true },
    MiniStatuslineModeVisual = { fg = '#000000', bg = '#C792EA', bold = true },
    MiniSurround = { fg = '#86A5FF', bg = '#262E47' },
    MiniTablineCurrent = { fg = '#86A5FF', bg = '#0C0E19', bold = true },
    MiniTablineVisible = { fg = '#C7D5FF', bg = '#000000' },
    MiniTablineHidden = { fg = '#576DAF', bg = '#000000' },
    MiniTablineModifiedCurrent = { fg = '#C792EA' },
    MiniHint = { fg = '#89DDFF', bg = '#15182B' },
    MiniInfo = { fg = '#89DDFF', bg = '#15182B' },
    MiniWarn = { fg = '#FFCB6B', bg = '#15182B' },
    MiniError = { fg = '#DD5074', bg = '#15182B' },
    HopNextKey = { fg = '#86A5FF', bold = true },
    HopUnmatched = { fg = '#576DAF' },
    LeapLabelPrimary = { fg = '#86A5FF', bold = true },
    LeapLabelSecondary = { fg = '#C792EA', bold = true }
  }
end

return M
